package dev.lumen.core.category

import dev.lumen.core.model.AppKey

/**
 * GENERATED — do not edit.
 *
 * Source: `tools/registry-builder/registry.tsv`
 * Regenerate: `python3 tools/registry-builder/build-registry.py`
 *
 * The TSV is the human-reviewed artefact (`docs/plan.md`: "top-500
 * human-reviewed registry"); this file is its compiled form. A generated
 * Kotlin map rather than a runtime resource because :core is commonMain and
 * resource loading differs per platform — this is identical everywhere and
 * cannot fail to load on one of them.
 *
 * Entries: 185
 */
object GeneratedRegistry : CategoryRegistry {

    override fun lookup(appKey: AppKey): Category? =
        BY_KEY[appKey.value.trim().lowercase()]

    /** Every key in the registry, for the corpus test and tooling. */
    val keys: Set<String> get() = BY_KEY.keys

    private val BY_KEY: Map<String, Category> = mapOf(
        "1password" to Category.Utilities,
        "alacritty" to Category.Development,
        "android-studio" to Category.Development,
        "bitwarden" to Category.Utilities,
        "blender" to Category.Media,
        "brave-browser" to Category.Browsing,
        "chromium" to Category.Browsing,
        "code" to Category.Development,
        "code-oss" to Category.Development,
        "com.1password.1password" to Category.Utilities,
        "com.adobe.lightroomclassiccc7" to Category.Media,
        "com.adobe.photoshop" to Category.Media,
        "com.agilebits.onepassword7" to Category.Utilities,
        "com.agiletortoise.drafts-osx" to Category.Writing,
        "com.amazon.kindle" to Category.Reading,
        "com.android.chrome" to Category.Browsing,
        "com.apple.activitymonitor" to Category.Utilities,
        "com.apple.appstore" to Category.Utilities,
        "com.apple.calculator" to Category.Utilities,
        "com.apple.dt.xcode" to Category.Development,
        "com.apple.facetime" to Category.Communication,
        "com.apple.finalcut" to Category.Media,
        "com.apple.finder" to Category.Utilities,
        "com.apple.ibooks" to Category.Reading,
        "com.apple.ical" to Category.Utilities,
        "com.apple.ichat" to Category.Communication,
        "com.apple.iwork.pages" to Category.Writing,
        "com.apple.mail" to Category.Communication,
        "com.apple.mobilesms" to Category.Communication,
        "com.apple.music" to Category.Media,
        "com.apple.news" to Category.Reading,
        "com.apple.notes" to Category.Writing,
        "com.apple.photos" to Category.Media,
        "com.apple.podcasts" to Category.Media,
        "com.apple.preview" to Category.Reading,
        "com.apple.quicktimeplayerx" to Category.Media,
        "com.apple.reminders" to Category.Utilities,
        "com.apple.safari" to Category.Browsing,
        "com.apple.screensharing" to Category.Utilities,
        "com.apple.systempreferences" to Category.Utilities,
        "com.apple.terminal" to Category.Development,
        "com.apple.tv" to Category.Media,
        "com.bitwarden.desktop" to Category.Utilities,
        "com.blackmagic-design.davinciresolve" to Category.Media,
        "com.blizzard.worldofwarcraft" to Category.Games,
        "com.brave.browser" to Category.Browsing,
        "com.discord" to Category.Communication,
        "com.docker.docker" to Category.Development,
        "com.epicgames.launcher" to Category.Games,
        "com.figma.desktop" to Category.Development,
        "com.flexibits.fantastical2.mac" to Category.Utilities,
        "com.github.electron" to Category.Development,
        "com.github.githubclient" to Category.Development,
        "com.google.android.gm" to Category.Communication,
        "com.google.android.studio" to Category.Development,
        "com.google.android.youtube" to Category.Media,
        "com.google.chrome" to Category.Browsing,
        "com.googlecode.iterm2" to Category.Development,
        "com.heroicgameslauncher.hgl" to Category.Games,
        "com.hnc.discord" to Category.Communication,
        "com.instapaper.instapaper" to Category.Reading,
        "com.jetbrains.clion" to Category.Development,
        "com.jetbrains.goland" to Category.Development,
        "com.jetbrains.intellij" to Category.Development,
        "com.jetbrains.pycharm" to Category.Development,
        "com.jetbrains.rider" to Category.Development,
        "com.jetbrains.webstorm" to Category.Development,
        "com.literatureandlatte.scrivener3" to Category.Writing,
        "com.lukilabs.lukiapp" to Category.Writing,
        "com.microsoft.edgemac" to Category.Browsing,
        "com.microsoft.onenote.mac" to Category.Writing,
        "com.microsoft.teams" to Category.Communication,
        "com.microsoft.teams2" to Category.Communication,
        "com.microsoft.vscode" to Category.Development,
        "com.microsoft.word" to Category.Writing,
        "com.mitchellh.ghostty" to Category.Development,
        "com.mojang.minecraftpe" to Category.Games,
        "com.neovide.neovide" to Category.Development,
        "com.netflix.mediaclient" to Category.Media,
        "com.netflix.netflix" to Category.Media,
        "com.notion.id" to Category.Writing,
        "com.obsproject.obs-studio" to Category.Media,
        "com.operasoftware.opera" to Category.Browsing,
        "com.plexapp.plex" to Category.Media,
        "com.pocket.pocket" to Category.Reading,
        "com.postmanlabs.mac" to Category.Development,
        "com.readdle.pdfexpert-mac" to Category.Reading,
        "com.readdle.smartemail" to Category.Communication,
        "com.reederapp.5.macos" to Category.Reading,
        "com.slack" to Category.Communication,
        "com.sourcetreeapp" to Category.Development,
        "com.spotify.client" to Category.Media,
        "com.sublimetext.4" to Category.Development,
        "com.tinyspeck.slackmacgap" to Category.Communication,
        "com.transmissionbt.transmission" to Category.Utilities,
        "com.ulyssesapp.mac" to Category.Writing,
        "com.valvesoftware.steam" to Category.Games,
        "com.vivaldi.vivaldi" to Category.Browsing,
        "com.whatsapp" to Category.Communication,
        "company.thebrowser.browser" to Category.Browsing,
        "dev.warp.warp-stable" to Category.Development,
        "discord" to Category.Communication,
        "docker" to Category.Development,
        "dolphin" to Category.Utilities,
        "element" to Category.Communication,
        "emacs" to Category.Development,
        "evince" to Category.Reading,
        "figma" to Category.Development,
        "firefox" to Category.Browsing,
        "firefox-esr" to Category.Browsing,
        "foot" to Category.Development,
        "gedit" to Category.Writing,
        "gimp" to Category.Media,
        "gnome-control-center" to Category.Utilities,
        "gnome-system-monitor" to Category.Utilities,
        "google-chrome" to Category.Browsing,
        "heroic" to Category.Games,
        "im.riot.app" to Category.Communication,
        "io.mpv.mpv" to Category.Media,
        "jetbrains-idea" to Category.Development,
        "jetbrains-idea-ce" to Category.Development,
        "jetbrains-pycharm" to Category.Development,
        "keepassxc" to Category.Utilities,
        "kitty" to Category.Development,
        "konsole" to Category.Development,
        "libreoffice" to Category.Writing,
        "libreoffice-writer" to Category.Writing,
        "lutris" to Category.Games,
        "md.obsidian" to Category.Writing,
        "microsoft-edge" to Category.Browsing,
        "minecraft-launcher" to Category.Games,
        "mpv" to Category.Media,
        "nautilus" to Category.Utilities,
        "net.lutris.lutris" to Category.Games,
        "notion-app" to Category.Writing,
        "nvim" to Category.Development,
        "obs" to Category.Media,
        "obsidian" to Category.Writing,
        "okular" to Category.Reading,
        "opera" to Category.Browsing,
        "org.alacritty" to Category.Development,
        "org.blender.blender" to Category.Media,
        "org.chromium.chromium" to Category.Browsing,
        "org.gimp.gimp" to Category.Media,
        "org.gnome.evince" to Category.Reading,
        "org.gnome.gedit" to Category.Writing,
        "org.gnome.nautilus" to Category.Utilities,
        "org.gnome.terminal" to Category.Development,
        "org.kde.kdenlive" to Category.Media,
        "org.keepassxc.keepassxc" to Category.Utilities,
        "org.libreoffice.script" to Category.Writing,
        "org.mozilla.firefox" to Category.Browsing,
        "org.prismlauncher.prismlauncher" to Category.Games,
        "org.pwmt.zathura" to Category.Reading,
        "org.qutebrowser.qutebrowser" to Category.Browsing,
        "org.remmina.remmina" to Category.Utilities,
        "org.signal.signal" to Category.Communication,
        "org.telegram.desktop" to Category.Communication,
        "org.telegram.messenger" to Category.Communication,
        "org.thunderbird.thunderbird" to Category.Communication,
        "org.videolan.vlc" to Category.Media,
        "org.zotero.zotero" to Category.Reading,
        "plexmediaplayer" to Category.Media,
        "postman" to Category.Development,
        "remmina" to Category.Utilities,
        "signal-desktop" to Category.Communication,
        "slack" to Category.Communication,
        "spotify" to Category.Media,
        "steam" to Category.Games,
        "sublime_text" to Category.Development,
        "systemsettings" to Category.Utilities,
        "telegram-desktop" to Category.Communication,
        "thunar" to Category.Utilities,
        "thunderbird" to Category.Communication,
        "transmission-gtk" to Category.Utilities,
        "us.zoom.videomeetings" to Category.Communication,
        "us.zoom.xos" to Category.Communication,
        "vim" to Category.Development,
        "vlc" to Category.Media,
        "vscodium" to Category.Development,
        "wezterm" to Category.Development,
        "whatsapp" to Category.Communication,
        "zathura" to Category.Reading,
        "zoom" to Category.Communication,
        "zotero" to Category.Reading,
    )
}
